### ISSUE TITLE
deal with old files in dropbox

### ISSUE THREAD

**Issue by jenni** [berlindiamonds/discourse-sync-to-dropbox#18]
We need to find a way to delete old files from dropbox, something like:
```
    def delete_old_remote_backups
      (dbx_files - [backup]).each do |f| # this needs to be tested
        dbx.delete("/#{folder_name}/#{filename}")
      end
    end
```

**Comment by kajatiger** [comment]
I think writing a test for dbx is not neccessary, cause we are not supposed to test API methods...

**Comment by jenni** [comment]
This issue is about deleting the files from Dropbox like the method you were working on google drive the last days. Why do you say about the tests? I thought the tests were written already?

**Comment by kajatiger** [comment]
because there is the comment `# needs to be tested ` in the code..

**Comment by kajatiger** [comment]
the dropbox API documentation doesn't have any useful methods to list all files without knowing the path
