### ISSUE TITLE
SyncBackupsToDropbox: Create one synchronizer per each backup

### ISSUE THREAD

**Issue by jenni** [berlindiamonds/discourse-sync-to-dropbox#3]
Modify the SyncBackupsToDropbox class to loop over all backups and create one synchronizer per backup.

**Comment by jen-v** [comment]
`module Jobs  
  class SyncBackupsToDropbox < ::Jobs::Base

  	sidekiq_options queue: 'low'

    def execute(args)
      ::DiscourseBackupToDropbox::DropboxSynchronizer.sync if SiteSetting.discourse_backups_to_dropbox_enabled
    end
  end
end`

**Comment by jenni** [comment]
```
module Jobs  
  class SyncBackupsToDropbox < ::Jobs::Base

  	sidekiq_options queue: 'low'

    def execute(args)
      ::DiscourseBackupToDropbox::DropboxSynchronizer.sync if SiteSetting.discourse_backups_to_dropbox_enabled
    end
  end
end
```
